travis:
  secure:
    BINSTAR_TOKEN: YArshvtlbzIf1tf7zIzca2yssbwVfLbnNmienlnMS9W7AOyIjZAPezBKeXk+A05VRUfh56uQsrG8e2ZnXAuL5JSsVjwSfGvWQI2XeTFk7iAZN5VAaM3Xzup4ZVYDP8HtPYF39HlEPKbeVmzwp6xsl8sRYjXYU2oo5n/MmzFb09TELti5A7zmiGargIanqgz/VFfrjS9xiKQDYzrELlQROj6zg0OwO6hcnKymClQOg3ZW8Y3hlaornHiSrJuyAHq4S9ymbkUbKsox4w/ndgt04VFOp3lF+sNPE0FWPkYk2qy4X4IcWIfE2aiaFg1ccG2aRJXkCFduVsxA6iYPd9W8JlikeRh2BDllnBJGHD6VHgveyjZ6qxQGET7oVSgJSEvxPEhn/k7Sa4sUddrYO6Esa2EDQcHjvjneU32KcvglnyXpIDu0xRHJiu0pPVPtkKzxDBxX3/7z4hNQiOwtzi8miFsDZsRIFDxl24aBERmSiT4EJCZKnmiNjbtq6pIH+UHOK/G1ckZWjC7jnvbR+WkJ+Od+nLooIc6dsImTooxCepygYs1BKHPT6tbsoQiWzwb0jlNS+Sjw2Nb4ADrP+9JqmcCXqE6ye5s9G0mTAMW4NvX1WuZYlMqeG/3ewn/QQqAKh43M3BJuI1tXEqBv4tL7rthgxaNy2dtgpc2LF880J1U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
